packages:
  - apps/*
  - packages/*

linkWorkspacePackages: false
saveWorkspaceProtocol: rolling
disallowWorkspaceCycles: true
failIfNoMatch: true
autoInstallPeers: false
strictPeerDependencies: true
engineStrict: true

requiredScripts:
  - build
  - typecheck
  - test

allowBuilds:
  cpu-features: true
  esbuild: true
  protobufjs: true
  ssh2: true
